receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  debug:
    verbosity: detailed
  awsxray:
    region: us-west-2
  awsemf:
    region: us-west-2

service:
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - debug
        - awsxray
    metrics:
      receivers:
        - otlp
      exporters:
        - debug
        - awsemf
